models:
  paraformer:
    model: "iic/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch"
    model_revision: "v2.0.4"
    vad_model: "iic/speech_fsmn_vad_zh-cn-16k-common-pytorch"
    vad_model_revision: "v2.0.4"
    punc_model: "iic/punc_ct-transformer_zh-cn-common-vocab272727-pytorch"
    punc_model_revision: "v2.0.4"
    spk_model: "iic/speech_campplus_sv_zh-cn_16k-common"
    spk_model_revision: "v2.0.2"
    disable_update: True

  FunASRNano:
    model: "FunAudioLLM/Fun-ASR-Nano-2512"
    vad_model: 'iic/speech_fsmn_vad_zh-cn-16k-common-pytorch'
    vad_kwargs: {'max_single_segment_time': 30000}
    disable_update: True
    trust_remote_code: True

  FunASRMLTNano:
    model: "FunAudioLLM/Fun-ASR-MLT-Nano-2512"
    vad_model: 'iic/speech_fsmn_vad_zh-cn-16k-common-pytorch'
    vad_kwargs: {'max_single_segment_time': 30000}
    disable_update: True
    trust_remote_code: True